name: Daily Commit

on:
  schedule:
    - cron: '0 13 * * *'   # Se ejecuta todos los dÃ­as 13:00 UTC
    - cron: '0 04 * * *'   
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Update: $(date)" >> log.txt

      - name: Commit and Push
        run: |
          git config user.name "Luthors"
          git config user.email "luis.g.toro@gmail.com"
          git add .
          git commit -m "Auto update $(date)" || echo "No changes"
          git push
